### ISSUE TITLE
How to customize the resume.tex template and change the language

### ISSUE THREAD

**Issue by aucru** [varbhat/cvtek#1]
Do I need to write a new template and upload it to the template directory and recompile it?

**Comment by varbhat** [comment]
Hey @J1nH4ng,

`cvtek` by default uses template defined here https://github.com/varbhat/cvtek/blob/main/templates/resume.tex.tmpl . You can copy that file, modify as you wish, and to use the modified template, pass the `--template pathtotemplate` flag to `cvtek`.

Hope this helps you.

**Comment by varbhat** [comment]
I am closing this issue. If you still have doubts, feel free to message/comment below.

**Comment by J1nH4ng** [comment]
Sincerely thank you for your answers
